proxyserver/src/main/java/com/lyft/data/proxyserver/wrapper/MultiReadHttpServletRequest.java
In current implementation, when downstream posts a content with "\r\n", the body length is changed.  
Which makes request proxied to upstream has "Content-Length" > body length  
So upstream server will wait forever (until timeout) for the request.
I have tested this pull request.
=> FIX: Fix body length changed

gateway/src/main/resources/template/gateway-view.ftl
In current implementation, Chinese string in web ui doesn't display correctly.  
I have tested the fix in Chrome.
=> FIX: Chinese string doesn't display correctly

gateway/src/main/java/com/lyft/data/gateway/handler/QueryIdCachingProxyHandler.java
DataGrip requires db version to validate connection to presto. Whitelisting `/v1/info` so that Datagrip can connect via presto-gateway.
=> Allowing /v1/info to be routed by gateway

.gitignore, gateway/src/main/java/com/lyft/data/gateway/config/RequestRouterConfiguration.java, gateway/src/main/java/com/lyft/data/gateway/module/GatewayProviderModule.java, pom.xml, proxyserver/src/main/java/com/lyft/data/proxyserver/ProxyServer.java, proxyserver/src/main/java/com/lyft/data/proxyserver/ProxyServerConfiguration.java
@puneetjaiswal - I'm using this along with a keystore containing a self-signed certificate to test potential SSL connection drops, and so far haven't reproduced the problem. Just sharing this here as an easy surface for you to review my test methodology, but I don't intend for this to be merged.
=> SSL listener support for presto-gateway to test connection failures over HTTPS

gateway/src/main/java/com/lyft/data/gateway/handler/QueryIdCachingProxyHandler.java
do more check for statement status fix queryid get error for support prestosql/presto, api resouce   link https://github.com/prestosql/presto/blob/master/presto-main/src/main/java/io/prestosql/server/protocol/ExecutingStatementResource.java
=> Improve query id extraction for /v1/statement/.. endpoints

.gitignore, baseapp/pom.xml, gateway-ha/gateway-ha-config.yml, gateway-ha/pom.xml, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/ActiveClusterMonitor.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/ClusterStats.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/HealthChecker.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/PrestoClusterStatsObserver.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/PrestoQueueLengthChecker.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/module/ClusterStateListenerModule.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/HaQueryHistoryManager.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/HaRoutingManager.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/PrestoQueueLengthRoutingTable.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/QueryHistoryManager.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/router/TestPrestoQueueLengthRoutingTable.java, pom.xml, proxyserver/pom.xml
1. Introduced Listeners for the Active Cluster Monitor , The Health Checker & RoutingTable are listners to the stats collected frm the Active Cluster Monitor.
2. The PrestoQueueLengthRoutingTable is an extention of the HARoutingManager that gets list of all active backends along with queue depth. It assigns a weight to each cluster relative to the most queued up cluster. The most queued up cluster's weight is adjusted such that it handles the following cases
a. There is a huge difference between the least queued up & most queued up cluster, in which case the most queued Up cluster is given a negligible wt such that it almost get no new requests.
b. there diff is not huge between least & most queued up in which case most queued Up cluster is given a small-ish  wt such that it get sonly a …
=> Presto Queue Length Based Routing Manager

gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/ActiveClusterMonitor.java, pom.xml
For https://jira.lyft.net/browse/DATA-9315, added logging for non 200 responses to help debugging issues with health check failures.
Also bumped up Lombok version so it works with JDK10+ due to https://github.com/rzwitserloot/lombok/issues/1651
=> Add metrics logging

gateway-ha/src/main/java/com/lyft/data/gateway/ha/handler/QueryIdCachingProxyHandler.java
This PR whitelists the `v1/cluster` API so that redirects from the query to the presto cluster render with the right details. Since this is currently not whitelisted, the UI shows a bunch of `NaN`s like this:
Issue to track this: https://github.com/lyft/presto-gateway/issues/88
=> whitelist cluster api for presto ui

gateway-ha/pom.xml, gateway-ha/src/main/java/com/lyft/data/gateway/ha/handler/QueryIdCachingProxyHandler.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/RoutingGroupSelector.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/router/TestRoutingGroupSelector.java
Define the `RoutingGroupSelector` interface as an abstraction to allow for custom routing group selectors in the future.
Currently it keeps the same behavior by using a selector that is based on the `X-Presto-Routing-Group` header. This is the first step towards https://github.com/lyft/presto-gateway/issues/62
=> Define RoutingGroupSelector interface for customizable routing

README.md, gateway-ha/README.md
Since the `removeBackend` function only takes in a single string [name](https://github.com/lyft/presto-gateway/blob/master/gateway-ha/src/main/java/com/lyft/data/gateway/ha/resource/HaGatewayResource.java#L40) argument, this PR updates the README under `gateway-ha` to properly reflect what a valid deletion command should be, and adds this same command to the main README for increased accessibility.
Signed-off-by: Derek Heldt-Werle <derek.heldt-werle@viasat.com>
=> Fixes deletion example in README

README.md, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/ActiveClusterMonitor.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/ClusterStats.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/config/ProxyBackendConfiguration.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/persistence/dao/GatewayBackend.java, gateway-ha/src/main/resources/gateway-ha-persistence.sql, gateway-ha/src/main/resources/template/gateway-view.ftl, gateway-ha/src/migrations/gateway-ha.sql, gateway-ha/src/test/java/com/lyft/data/gateway/ha/HaGatewayTestUtils.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/TestGatewayHaMulipleBackend.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/TestGatewayHaSingleBackend.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/router/TestHaGatewayManager.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/router/TestPrestoQueueLengthRoutingTable.java, proxyserver/src/main/java/com/lyft/data/proxyserver/ProxyServerConfiguration.java
When running Presto Gateway on Kubernetes pods in Google Cloud Platform the backend URL uses an internal endpoint for requests. This works fine until a user tries to use the URL on the Active Backends page in the UI. This uses the internal hostname and therefore cannot be reached by users outside of the network. To work around this I'd like to add an optional `externalUrl` field that can be used to point to an external hostname. The field could be passed in like this:
```
curl -X POST http://localhost:8080/entity\?entityType\=GATEWAY_BACKEND \
-d '{"name":"presto1", \
"proxyTo": "presto1.lyft.com", \
"externalUrl": "http://my-external-url.com", \
"active": true, \
"routingGroup": "adhoc"}'
curl -X POST http://localhost:8080/entity\?entityType\=GATEWAY_BACKEND \
-d '{"name":"presto2", \ …
```
=> Add ExternalUrl to Active Backends Page

README.md, baseapp/pom.xml, gateway-ha/pom.xml, gateway-ha/src/main/java/com/lyft/data/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/persistence/dao/ExactMatchSourceSelectors.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/persistence/dao/ResourceGroups.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/persistence/dao/ResourceGroupsGlobalProperties.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/persistence/dao/Selectors.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/resource/PrestoResource.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/HaResourceGroupsManager.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/ResourceGroupsManager.java, gateway-ha/src/main/resources/00-resource_groups.sql, gateway-ha/src/main/resources/gateway-ha-persistence.sql, gateway-ha/src/migrations/gateway-ha.sql, gateway-ha/src/test/java/com/lyft/data/gateway/ha/router/TestResourceGroupManager.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/router/TestResourceGroupsManager.java, pom.xml, proxyserver/pom.xml
Currently, we specify resource groups via a config file but we are now transitioning to specifying via database through the implementation of a CRUD API. The purpose of this change is to improve the overall time used to update resource groups. Previously, redeployment was necessary every time we needed to make a change (big or small) to the resource groups.
First, I implemented the backend by creating dao files for each of these four tables (resource_groups, selectors, resource_groups_global_properties, exact_source_match_selectors), integrating them to the API file, and writing unit tests for all dao files. Next, I created separate CRUD APIs for each table in PrestoResource.java and tested them in the local Presto Gateway environment using CURL commands & Postman (specified in the …
=> Merging Resource Group Management code into master

README.md, gateway-ha/src/main/java/com/lyft/data/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/resource/PrestoResource.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/HaResourceGroupsManager.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/ResourceGroupsManager.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/router/TestResourceGroupsManager.java
Currently, selectors are updated and deleted solely based off their resourceGroupId. This functionality is not representative of the actual relationship between selectors and resource groups, which is many to one (there can be multiple selectors with the same resource group id). With this change, the current selector's json must also be specified in addition to the updated selector's json - if the current selector's json does not exist, a new selector is created.
Relevant PRs: https://github.com/lyft/presto-gateway/pull/114
=> Updating Selector's Update and Delete Functionality

baseapp/pom.xml, gateway-ha/pom.xml, gateway-ha/src/main/java/com/lyft/data/gateway/ha/handler/QueryIdCachingProxyHandler.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/handler/TestQueryIdCachingProxyHandler.java, pom.xml, proxyserver/pom.xml
Presto Uses "X-Forwarded-Host" to determine the nextURi & InfoURI. These headers are set correctly on the outgoing Proxy request as we are using ProxyServlet.Transparent . Reference : https://github.com/lyft/presto-gateway/blob/master/proxyserver/src/main/java/com/lyft/data/proxyserver/ProxyServletImpl.java 
This PR explicitly sets the Host Header to the host name of the backend presto cluster vs preserving the Host of the gateway itself. This ensures that we dont run into 400 Bad request Issues if there is an LB fronting the backend Presto cluster.
=> Setting forwarded host correctly

gateway-ha/src/main/java/com/lyft/data/gateway/ha/handler/QueryIdCachingProxyHandler.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/RoutingGroupSelector.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/TestGatewayHaMulipleBackend.java
Trino uses `X-Trino` headers instead of `X-Presto` headers. Gateway uses `X-Presto-User` and `X-Presto-Source` to determine the user and source of query. Gateway would continue to work, however, these important metrics would not get recorded, for any query coming from a Trino client.
Check for either `X-Trino-User` or `X-Presto-User` is done on each query request. Similar check is done for `X-Presto-Source` and `X-Trino-Source`. Client libraries can specify `X-Trino-Routing-Group` instead of `X-Presto-Routing-Group`, for uniformity.
Fixes #134.
=> Add support for Trino

README.md
Small change to the README - the create APIs should not require a `resource_group_id` as it is automatically incremented by the database.
=> Updating instructions for create functions

README.md, baseapp/pom.xml, gateway-ha/gateway-ha-config.yml, gateway-ha/pom.xml, gateway-ha/src/main/java/com/lyft/data/gateway/ha/config/HaGatewayConfiguration.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/config/RoutingRulesConfiguration.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/RoutingGroupSelector.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/router/TestRoutingGroupSelector.java, gateway-ha/src/test/resources/rules/routing_rules.yml, gateway-ha/src/test/resources/rules/routing_rules_atomic.yml, gateway-ha/src/test/resources/rules/routing_rules_composite.yml, gateway-ha/src/test/resources/rules/routing_rules_if_statements.yml, gateway-ha/src/test/resources/rules/routing_rules_priorities.yml, pom.xml, proxyserver/pom.xml
Currently, presto-gateway routes requests to backends by reading the `X-Trino-Routing-Group` header. 
This PR introduces a routing rules engine feature, allowing users to define custom logic to route queries. These rules are separated from application logic and kept in a config file, allowing for dynamic rule changes. These rules can use any method of a `HttpServletRequest` object, including get headers (https://trino.io/docs/current/develop/client-protocol.html)
=> Add routing rules engine feature

README.md
Adding Trino-gateway use cases.
tech blog links to zomato and shopify use cases.
=> Adding Trino-gateway use cases - tech blogs

README.md, baseapp/pom.xml, gateway-ha/pom.xml, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/PrestoQueueLengthChecker.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/PrestoQueueLengthRoutingTable.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/router/TestPrestoQueueLengthRoutingTable.java, pom.xml, proxyserver/pom.xml
Changes: 
- Use running count as a fallback if queue count are the same. This doesn't change the core algo, just passes in running-counts if queuecounts are the same for a routing group.
- Some other minor changes/clean-up/version fixes to resolve some build errors.
=> QueueBasedRouting: Use Running Count as fallback logic

baseapp/pom.xml, gateway-ha/pom.xml, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/ActiveClusterMonitor.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/ClusterStats.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/PrestoQueueLengthChecker.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/handler/QueryIdCachingProxyHandler.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/PrestoQueueLengthRoutingTable.java, gateway-ha/src/main/java/com/lyft/data/gateway/ha/router/RoutingManager.java, gateway-ha/src/test/java/com/lyft/data/gateway/ha/router/TestPrestoQueueLengthRoutingTable.java, pom.xml, proxyserver/pom.xml
Support Routing to cluster with the least queue for the User, fallback to existing Cluster Queue based Routing approach if user level queue size are equal/no-queue.
Makes use of "ui/api/query?state=QUEUED"  on the coordinator to fetch the current queued queries on the cluster. 
This is internal change to the routing manager but given this is a sizable change, I plan to bump up the version to `1.9.0` with this release
=> Add Support for User Queue Level Routing

baseapp/pom.xml, gateway-ha/pom.xml, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/ActiveClusterMonitor.java, pom.xml, proxyserver/pom.xml
Increase the default thread-pool size to accommodate latency-sensitive observers for large number of trino clusters.
=> Update thread pool for ClusterMonitor

baseapp/pom.xml, gateway-ha/pom.xml, gateway-ha/src/main/java/com/lyft/data/gateway/ha/clustermonitor/PrestoQueueLengthChecker.java, pom.xml, proxyserver/pom.xml
We generate `healthy` flag as part of ClusterMonitor but don't use it for routing i.e. still route queries to that cluster. 
This filters out unhealthy clusters from queue based routing logic + adds some npe checks.
=> Filter out unhealthy clusters from queue based routing

baseapp/pom.xml, gateway-ha/pom.xml, pom.xml, proxyserver/pom.xml
Bumping patch versions for dependencies. This should be backward compatible/safe : 
- Jetty Patch version update to latest 9.4.x released 6/22 : https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.48.v20220622 . 
- Bump mysql-connector-java from 8.0.17 to 8.0.28
- Bump httpclient from 4.5.1 to 4.5.13 
-
=> Update Patch Dependencies Versions

baseapp/pom.xml, gateway-ha/pom.xml, pom.xml, proxyserver/pom.xml
Follow-up to https://github.com/lyft/presto-gateway/pull/179 . A couple of other patch versions updates.
Jetty Patch version update to latest 9.4.x released 6/22 : https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.48.v20220622 in gateway-ha
Dropwizard patch version to  1.3.29  to pull in https://github.com/dropwizard/dropwizard/pull/3527
=> Bump Patch Versions

baseapp/pom.xml, gateway-ha/pom.xml, pom.xml, proxyserver/pom.xml
mysql-connector upgrade seems to be creating issues with non-ascii chars in query-text. For now, reverting only this back to 8.0.17.
=> mysql-connector to 8.0.17

README.md
Updating README to reflect the following: presto-gateway has been absorbed by trino-gateway, which is in active development and officially adopted by trinodb: https://github.com/trinodb/trino-gateway
=> Point to official Trino Gateway repo
